# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
