# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20171206_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='tickleFK',
            field=models.TextField(max_length=1000),
        ),
    ]
