# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_auto_20171209_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='UserFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_UserFK', to='newsapp.Users'),
        ),
    ]
