# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_auto_20171210_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickleFK', models.TextField(max_length=1000, null=True)),
                ('text', models.TextField()),
                ('Date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_UserFK', to='newsapp.Users')),
            ],
        ),
    ]
