# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_article_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cat',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=10000),
        ),
    ]
