# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_article_imagelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tickleFK',
        ),
        migrations.RemoveField(
            model_name='like',
            name='tickleFK',
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_ArticleFK', to='newsapp.Article'),
        ),
        migrations.AddField(
            model_name='like',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_ArticleFK', to='newsapp.Article'),
        ),
    ]
